# Step 1: Build stage
FROM node:14.16.0-alpine3.13 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# http://idMyServer:PORT 
ENV REACT_APP_API_URL=http://104.131.24.150:3001/api
RUN npm run build

# Step 2: Production
FROM nginx:1.12-alpine
RUN addgroup app && adduser -S -G app app
RUN mkdir /app && chown app:app /app
USER app
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]